const REQUEST_CONSULT_KEYS_JSON = 'REQUEST_CONSULT_KEYS_JSON';
const RECEIVE_CONSULT_KEYS_JSON = 'RECEIVE_CONSULT_KEYS_JSON';
const SET_CONSULT_KEYS = 'SET_CONSULT_KEYS';

export default {
  REQUEST_CONSULT_KEYS_JSON,
  RECEIVE_CONSULT_KEYS_JSON,
  SET_CONSULT_KEYS,
};
