const REQUEST_CONSULT_INFO = 'REQUEST_CONSULT_INFO';
const RECEIVE_CONSULT_INFO = 'RECEIVE_CONSULT_INFO';
const SET_INVALID_CONSULT_INFO = 'SET_INVALID_CONSULT_INFO';

export default {
  REQUEST_CONSULT_INFO,
  RECEIVE_CONSULT_INFO,
  SET_INVALID_CONSULT_INFO,
};
