const REQUEST_CONSULT_INFO = 'REQUEST_CONSULT_INFO';
const RECEIVE_CONSULT_INFO = 'RECEIVE_CONSULT_INFO';
const SET_INVALID_CONSULT_INFO = 'SET_INVALID_CONSULT_INFO';
const RESET_STATE = 'RESET_STATE';

export default {
  REQUEST_CONSULT_INFO,
  RECEIVE_CONSULT_INFO,
  RESET_STATE,
  SET_INVALID_CONSULT_INFO,
};
