const REQUEST_CHECKOUT = 'REQUEST_CHECKOUT';
const RECEIVE_CHECKOUT_SUCCESS = 'RECEIVE_CHECKOUT_SUCCESS';
const SET_CHECKOUT_ERROR = 'SET_CHECKOUT_ERROR';
const RESET_STATE = 'RESET_STATE';

export default {
  REQUEST_CHECKOUT,
  RECEIVE_CHECKOUT_SUCCESS,
  SET_CHECKOUT_ERROR,
  RESET_STATE,
};
